---
title: "Load Models"
author: "Mac Wierda"
date: "2025-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(5400)
```

## Load Models

### Data Setup
```{r}
#import libraries
library(forecast)

# read in energy/weather data
# ew.df = energy weather data frame
ew.df = read.csv('./energy_weather_data.csv')

# test data
ew.df.test = ew.df[(4427-143):4427,]

# training data; decided to just remove test data, rather than replace with an average response
ew.df.train = ew.df[-(4427-143):-4427,]

# first model only needs the datetime and actual load data, not temp or anything else
ew.df.train.load = ew.df.train[,c(1,3)]
ew.df.test.load = ew.df.test[,c(1,3)]

# create time series versions of data sets with hourly frequency
ew.df.train.load.ts = ts(ew.df.train.load$total.load.actual, frequency=24)
ew.df.test.load.ts = ts(ew.df.test.load$total.load.actual, frequency=24)
```

## Finding correct ARIMA model
```{r}
# visualization of load data
plot(ew.df.train.load.ts, type='l', xlab='time', ylab='load')

# looking to make an 'arima' model of the data = Auto-Regressive Integrated Moving Average
# Forecast library contains a lot of convienent methods
# ggtsdisplay plots the times series with ACF and PACF graphs
# the base data does have changing variance, so we'll plot it with one difference
# plot with 1 difference below
ts.diff = diff(ew.df.train.load.ts)

ggtsdisplay(ts.diff)

# data is cleary stationary now: mean, varaince, and autocorrelation don't change over time
# ACF = ts correlation with lagged version of itself; starts at lag 0 == correlation with itself => 1
# PACF = additional correlation explained by each successive lag term
# anything outside blue area = 95% significance threshold
# ACF plot has several significant lags, but when we check the PACF we see that it's primarily lag=1 that is
#   significant
# Thus, lag 1 should be sufficient. And if we run the 'auto.arima' function below, it'll calculate the best result for us

if (!exists('arima.res.auto')) {
  arima.res.auto = auto.arima(ts.diff)
}
arima.res.auto
checkresiduals(arima.res.auto)

# We get ARIMA(1,0,1)(2,0,0) with zero mean
# unfortunately we still have correlation in our data; this is the best we can do, it seems, so our result
#   isn't gonna be super conclusive compared to the original paper
```

## Fitting individual regr models for model 2
```{r}
# basic regression and qq plot comparison indicates it's a fairly linear relationship, so don't need
#   to use a different model
plot(lm(total.load.actual ~ temp, ew.df.train))

# can include regression in auto.arima with the 'xreg' parameter
aa.x = auto.arima(ts.diff, xreg=ew.df.train[1:4282,6])
aa.x

```

